<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<Version>1.0.0</Version>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Lateral.CMS.Application\Lateral.CMS.Application.csproj" />
	</ItemGroup>
</Project>
