// <auto-generated />
using System;
using Lateral.CMS.Infrastructure.Data.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lateral.CMS.Infrastructure.Data.SqlServer.Migrations
{
    [DbContext(typeof(CmsDbContext))]
    partial class CmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lateral.CMS.Domain.Entities.Content.CmsEntity", b =>
                {
                    b.Property<Guid>("CmsEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AddedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CmsEntityStatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DisabledByAdminDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisabledByAdminUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDisabledByAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastEventTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("LastPublishedVersion")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("CmsEntityId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("CmsEntityStatusId", "IsDisabledByAdmin", "ExternalId");

                    b.ToTable("CmsEntity", "Content", t =>
                        {
                            t.HasCheckConstraint("CK_CmsEntity_Payload_IsJson", "ISJSON([Payload]) > 0");
                        });
                });

            modelBuilder.Entity("Lateral.CMS.Domain.Entities.Content.CmsEntityTombstone", b =>
                {
                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("AddedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DeletedTimestamp")
                        .IsConcurrencyToken()
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ExternalId");

                    b.ToTable("CmsEntityTombstone", "Content");
                });

            modelBuilder.Entity("Lateral.CMS.Domain.Entities.Ingestion.CmsEvent", b =>
                {
                    b.Property<long>("CmsEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CmsEventId"));

                    b.Property<int>("Attempts")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BatchIndex")
                        .HasColumnType("int");

                    b.Property<int>("CmsEventStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("CmsEventTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EventTimestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("NextAttemptDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReceivedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ReceivedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.HasKey("CmsEventId");

                    b.HasIndex("BatchId");

                    b.HasIndex("ExternalId");

                    b.HasIndex("CmsEventStatusId", "NextAttemptDate", "EventTimestamp");

                    b.ToTable("CmsEvent", "Ingestion", t =>
                        {
                            t.HasCheckConstraint("CK_CmsEvent_Payload_IsJson", "ISJSON([Payload]) > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
